### ISSUE TITLE
SAST Tools listed on 2 pages - Suggest maintaining only on 1

### ISSUE THREAD

**Issue by davewichers** [OWASP/www-community#232]
I've been maintaining this page:

https://github.com/OWASP/www-community/blob/master/pages/Source_Code_Analysis_Tools.md

and I notice that this page has a list of SAST tools too:

https://github.com/OWASP/www-community/blob/master/pages/controls/Static_Code_Analysis.md

This seems redundant, hard to maintain. I suggest that the list of tools be maintained on the 1st page above, and the 2nd page simply reference the 1st. To me the 2nd page should simply describe what Static Code Analysis IS.

**Comment by kingthorin** [comment]
This [data se](https://github.com/OWASP/www-community/blob/master/_data/vulnerability_scanning_tools.yml) should probably be made to include a `type` attribute, then an include setup that filters based on type, so that the apps can be displayed consistently wherever needed.

Also if one of those pages is removed a redirect should be put in its place, or `redirect_from`set on the one that's kept.
