### ISSUE TITLE
Entropy recomendation for Insufficient Session-ID Length should be explained

### ISSUE THREAD

**Issue by mtausig** [OWASP/www-community#291]
The entropy recomendations for the [Insufficient Session-ID Length](pages/vulnerabilities/Insufficient_Session-ID_Length.md) vulnerability state that 

> Assuming that the session identifiers are being generated using a good source of random numbers, we will estimate the number of bits of entropy in a session identifier to be half the total number of bits in the session identifier.

Since this is a non-obvious claim and the reasoning behind it elludes me, this claim should be backed up by a source link and/or some explanation.

**Comment by scsibug** [comment]
The reason bits of entropy is less than "number of bits in the session identifier" is because of the encoding used.  If you assume that session identifiers are encoded as ASCII hexadecimal digits (Base16 encoding), then each 1 byte of the session identifier can encode 4 bits of data/entropy.  See [RFC4648](https://tools.ietf.org/html/rfc4648#section-8) for a full explanation of hexadecimal encoding.

In the context of HTTP cookies (ASCII encoded), we have to assume some additional space is needed to represent a byte array of random data.  One of the least compact encodings is hexadecimal, which makes it the "safest" assumption to start with if we want to give a recommendation for how many bytes a session identifier should be.  If a system uses base64 encoded session ID's, 128 bits (16 bytes) long, they will be able to store 96 bits of entropy.

So, in summary:  Hexadecimal is one of the least efficient binary-to-ASCII encodings in common use.  Since it is 50% efficient, if we double the number of bits of desired entropy (64 bits), we get a sensible lower bound for the size of the encoded session identifier (128 bits).

Agreed that the article should explain the reasoning behind the statement.  It would probably suffice to mention that a hexadecimal encoding is 50% efficient, and requires double the amount of bytes to encode a given amount of entropy.
